#!/usr/bin/env bash
#MISE description="Stop api, frontend and databases"

lsof -ti:8080 | xargs kill -9 2>/dev/null || true
lsof -ti:3000 | xargs kill -9 2>/dev/null || true
docker compose -f docker-compose.dev.yml down
